package com.demo.domain;

import java.util.Date;

public class TaskTableField {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_TF_ID
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private Integer taskTfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_TABLE_ID
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private Integer taskTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_TABLE_NAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String taskTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_TABLE_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String taskTableByname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_TABLE_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String taskTableDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_FIELD
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String taskField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.TASK_FIELD_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String taskFieldDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.FIELD_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String fieldByname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.PK_SERIAL
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String pkSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.CREATE_USER
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.CREATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.UPDATE_USER
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table_field.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_TF_ID
     *
     * @return the value of task_table_field.TASK_TF_ID
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public Integer getTaskTfId() {
        return taskTfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_TF_ID
     *
     * @param taskTfId the value for task_table_field.TASK_TF_ID
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskTfId(Integer taskTfId) {
        this.taskTfId = taskTfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_TABLE_ID
     *
     * @return the value of task_table_field.TASK_TABLE_ID
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public Integer getTaskTableId() {
        return taskTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_TABLE_ID
     *
     * @param taskTableId the value for task_table_field.TASK_TABLE_ID
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskTableId(Integer taskTableId) {
        this.taskTableId = taskTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_TABLE_NAME
     *
     * @return the value of task_table_field.TASK_TABLE_NAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getTaskTableName() {
        return taskTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_TABLE_NAME
     *
     * @param taskTableName the value for task_table_field.TASK_TABLE_NAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskTableName(String taskTableName) {
        this.taskTableName = taskTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_TABLE_BYNAME
     *
     * @return the value of task_table_field.TASK_TABLE_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getTaskTableByname() {
        return taskTableByname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_TABLE_BYNAME
     *
     * @param taskTableByname the value for task_table_field.TASK_TABLE_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskTableByname(String taskTableByname) {
        this.taskTableByname = taskTableByname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_TABLE_DESCRIBE
     *
     * @return the value of task_table_field.TASK_TABLE_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getTaskTableDescribe() {
        return taskTableDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_TABLE_DESCRIBE
     *
     * @param taskTableDescribe the value for task_table_field.TASK_TABLE_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskTableDescribe(String taskTableDescribe) {
        this.taskTableDescribe = taskTableDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_FIELD
     *
     * @return the value of task_table_field.TASK_FIELD
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getTaskField() {
        return taskField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_FIELD
     *
     * @param taskField the value for task_table_field.TASK_FIELD
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskField(String taskField) {
        this.taskField = taskField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.TASK_FIELD_DESCRIBE
     *
     * @return the value of task_table_field.TASK_FIELD_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getTaskFieldDescribe() {
        return taskFieldDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.TASK_FIELD_DESCRIBE
     *
     * @param taskFieldDescribe the value for task_table_field.TASK_FIELD_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setTaskFieldDescribe(String taskFieldDescribe) {
        this.taskFieldDescribe = taskFieldDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.FIELD_BYNAME
     *
     * @return the value of task_table_field.FIELD_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getFieldByname() {
        return fieldByname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.FIELD_BYNAME
     *
     * @param fieldByname the value for task_table_field.FIELD_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setFieldByname(String fieldByname) {
        this.fieldByname = fieldByname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.PK_SERIAL
     *
     * @return the value of task_table_field.PK_SERIAL
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getPkSerial() {
        return pkSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.PK_SERIAL
     *
     * @param pkSerial the value for task_table_field.PK_SERIAL
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setPkSerial(String pkSerial) {
        this.pkSerial = pkSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.CREATE_USER
     *
     * @return the value of task_table_field.CREATE_USER
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.CREATE_USER
     *
     * @param createUser the value for task_table_field.CREATE_USER
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.CREATE_DATE
     *
     * @return the value of task_table_field.CREATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.CREATE_DATE
     *
     * @param createDate the value for task_table_field.CREATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.UPDATE_USER
     *
     * @return the value of task_table_field.UPDATE_USER
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.UPDATE_USER
     *
     * @param updateUser the value for task_table_field.UPDATE_USER
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table_field.UPDATE_DATE
     *
     * @return the value of task_table_field.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table_field.UPDATE_DATE
     *
     * @param updateDate the value for task_table_field.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:13:18 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}