package com.demo.domain;

import java.util.Date;
import java.util.List;

public class TaskTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.TASK_TABLE_ID
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private Integer taskTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.TABLE_TYPE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private Integer tableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.TASK_TABLE_NAME
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private String taskTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.TASK_TABLE_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private String taskTableByname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.TASK_TABLE_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private String taskTableDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.PK_SERIAL
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private String pkSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.CREATE_USER
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.CREATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.UPDATE_USER
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_table.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.TASK_TABLE_ID
     *
     * @return the value of task_table.TASK_TABLE_ID
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public Integer getTaskTableId() {
        return taskTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.TASK_TABLE_ID
     *
     * @param taskTableId the value for task_table.TASK_TABLE_ID
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setTaskTableId(Integer taskTableId) {
        this.taskTableId = taskTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.TABLE_TYPE
     *
     * @return the value of task_table.TABLE_TYPE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public Integer getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.TABLE_TYPE
     *
     * @param tableType the value for task_table.TABLE_TYPE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setTableType(Integer tableType) {
        this.tableType = tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.TASK_TABLE_NAME
     *
     * @return the value of task_table.TASK_TABLE_NAME
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public String getTaskTableName() {
        return taskTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.TASK_TABLE_NAME
     *
     * @param taskTableName the value for task_table.TASK_TABLE_NAME
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setTaskTableName(String taskTableName) {
        this.taskTableName = taskTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.TASK_TABLE_BYNAME
     *
     * @return the value of task_table.TASK_TABLE_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public String getTaskTableByname() {
        return taskTableByname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.TASK_TABLE_BYNAME
     *
     * @param taskTableByname the value for task_table.TASK_TABLE_BYNAME
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setTaskTableByname(String taskTableByname) {
        this.taskTableByname = taskTableByname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.TASK_TABLE_DESCRIBE
     *
     * @return the value of task_table.TASK_TABLE_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public String getTaskTableDescribe() {
        return taskTableDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.TASK_TABLE_DESCRIBE
     *
     * @param taskTableDescribe the value for task_table.TASK_TABLE_DESCRIBE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setTaskTableDescribe(String taskTableDescribe) {
        this.taskTableDescribe = taskTableDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.PK_SERIAL
     *
     * @return the value of task_table.PK_SERIAL
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public String getPkSerial() {
        return pkSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.PK_SERIAL
     *
     * @param pkSerial the value for task_table.PK_SERIAL
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setPkSerial(String pkSerial) {
        this.pkSerial = pkSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.CREATE_USER
     *
     * @return the value of task_table.CREATE_USER
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.CREATE_USER
     *
     * @param createUser the value for task_table.CREATE_USER
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.CREATE_DATE
     *
     * @return the value of task_table.CREATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.CREATE_DATE
     *
     * @param createDate the value for task_table.CREATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.UPDATE_USER
     *
     * @return the value of task_table.UPDATE_USER
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.UPDATE_USER
     *
     * @param updateUser the value for task_table.UPDATE_USER
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_table.UPDATE_DATE
     *
     * @return the value of task_table.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_table.UPDATE_DATE
     *
     * @param updateDate the value for task_table.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 28 15:09:04 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    //加一个属性 数据库中没有 
  	public String parameter;
  	public int taskTpId;
  	public int ruleGroupId;
  	private Integer taskDbId;
  	public int ruleId;
  	public List<TaskTableField> tfList;
  	public String taskViewSql;

	public String getParameter() {
		return parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	public int getTaskTpId() {
		return taskTpId;
	}

	public void setTaskTpId(int taskTpId) {
		this.taskTpId = taskTpId;
	}

	public int getRuleGroupId() {
		return ruleGroupId;
	}

	public void setRuleGroupId(int ruleGroupId) {
		this.ruleGroupId = ruleGroupId;
	}

	public Integer getTaskDbId() {
		return taskDbId;
	}

	public void setTaskDbId(Integer taskDbId) {
		this.taskDbId = taskDbId;
	}

	public int getRuleId() {
		return ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	public List<TaskTableField> getTfList() {
		return tfList;
	}

	public void setTfList(List<TaskTableField> tfList) {
		this.tfList = tfList;
	}

	public String getTaskViewSql() {
		return taskViewSql;
	}

	public void setTaskViewSql(String taskViewSql) {
		this.taskViewSql = taskViewSql;
	}
  	
  	
    
}